### ISSUE TITLE
显示插件安装成功但是插件设置中没有，重新搜索仍然是未安装

### ISSUE THREAD

**Issue by muxinxy** [terwer/siyuan-plugin-picgo#163]
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/32673109/7ce5d5be-d1df-47da-bdd3-cd4e30b73697)
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/32673109/8a46e37b-a57b-4d6a-bdba-4c6377cd9959)

picgo日志：

2023-10-03 12:05:13 [PicGo SUCCESS] 插件安装成功 
2023-10-03 12:05:13 [PicGo ERROR] 
------Error Stack Begin------
Error: Cannot find module './bundle/client-sso-oidc-node'
Require stack:
- D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\token-providers\dist-cjs\index.js
- D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-sso\dist-cjs\resolveSSOCredentials.js
- D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-sso\dist-cjs\fromSSO.js
- D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-sso\dist-cjs\index.js
- D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-ini\dist-cjs\resolveSsoCredentials.js
- D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-ini\dist-cjs\resolveProfileData.js
- D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-ini\dist-cjs\fromIni.js
- D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-ini\dist-cjs\index.js
- D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-node\dist-cjs\defaultProvider.js
- D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-node\dist-cjs\index.js
- D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\client-sts\dist-cjs\runtimeConfig.js
- D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\client-sts\dist-cjs\STSClient.js
- D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\client-sts\dist-cjs\index.js
- D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\client-s3\dist-cjs\runtimeConfig.js
- D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\client-s3\dist-cjs\S3Client.js
- D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\client-s3\dist-cjs\index.js
- D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\picgo-plugin-s3\dist\uploader.js
- D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\picgo-plugin-s3\dist\index.js
- D:\Documents\SiYuan\data\plugins\siyuan-plugin-picgo\libs\sy-picgo-core\syPicgo.js
- electron/js2c/renderer_init
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at o._resolveFilename (node:electron/js2c/renderer_init:2:3879)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\token-providers\dist-cjs\index.js:4:22)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\token-providers\dist-cjs\index.js:9:3)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-sso\dist-cjs\resolveSSOCredentials.js:5:27)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-sso\dist-cjs\resolveSSOCredentials.js:56:3)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-sso\dist-cjs\fromSSO.js:7:33)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-sso\dist-cjs\fromSSO.js:63:3)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-sso\dist-cjs\index.js:4:22)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-sso\dist-cjs\index.js:9:3)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-ini\dist-cjs\resolveSsoCredentials.js:4:35)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-ini\dist-cjs\resolveSsoCredentials.js:19:3)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-ini\dist-cjs\resolveProfileData.js:7:33)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-ini\dist-cjs\resolveProfileData.js:34:3)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-ini\dist-cjs\fromIni.js:5:30)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-ini\dist-cjs\fromIni.js:12:3)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-ini\dist-cjs\index.js:4:22)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-ini\dist-cjs\index.js:6:3)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-node\dist-cjs\defaultProvider.js:5:35)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-node\dist-cjs\defaultProvider.js:17:3)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-node\dist-cjs\index.js:4:22)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\credential-provider-node\dist-cjs\index.js:6:3)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\client-sts\dist-cjs\runtimeConfig.js:7:36)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\client-sts\dist-cjs\runtimeConfig.js:50:3)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\client-sts\dist-cjs\STSClient.js:16:25)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\client-sts\dist-cjs\STSClient.js:44:3)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\client-sts\dist-cjs\index.js:5:22)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\client-sts\dist-cjs\index.js:13:3)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\client-s3\dist-cjs\runtimeConfig.js:6:22)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\client-s3\dist-cjs\runtimeConfig.js:58:3)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\client-s3\dist-cjs\S3Client.js:19:25)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\client-s3\dist-cjs\S3Client.js:52:3)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\client-s3\dist-cjs\index.js:5:22)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\@aws-sdk\client-s3\dist-cjs\index.js:14:3)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\picgo-plugin-s3\dist\uploader.js:6:21)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\picgo-plugin-s3\dist\uploader.js:113:3)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\picgo-plugin-s3\dist\index.js:5:36)
    at Object.<anonymous> (D:\Documents\SiYuan\data\storage\syp\picgo\node_modules\picgo-plugin-s3\dist\index.js:172:3)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at cK.getPlugin (D:\Documents\SiYuan\data\plugins\siyuan-plugin-picgo\libs\sy-picgo-core\syPicgo.js:376:11991)
    at cK.registerPlugin (D:\Documents\SiYuan\data\plugins\siyuan-plugin-picgo\libs\sy-picgo-core\syPicgo.js:376:11012)
    at D:\Documents\SiYuan\data\plugins\siyuan-plugin-picgo\libs\sy-picgo-core\syPicgo.js:556:6007
    at Array.forEach (<anonymous>)
    at pK.install (D:\Documents\SiYuan\data\plugins\siyuan-plugin-picgo\libs\sy-picgo-core\syPicgo.js:556:5973)
    at async D:\Documents\SiYuan\data\plugins\siyuan-plugin-picgo\libs\sy-picgo-core\syPicgo.js:556:34799
-------Error Stack End-------

**Comment by terwer** [comment]
![image](https://github.com/terwer/siyuan-plugin-picgo/assets/3259282/149b9580-233f-4aae-a09d-e8c84c0bbc33)
请检查配置，这是我的配置

```
/Users/terwer/Documents/app/node-v16.14.0-darwin-x64/bin
https://registry.npmmirror.com
```

如有问题可继续讨论。
